name: Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 13 * * 1"

jobs:
  build:
    name: Build (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        python-version: [ "3.9", "3.10" ,"3.11", "3.12", "3.13" ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Micromamba ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: TEST
          init-shell: bash
          create-args: >-
            python=${{ matrix.python-version }} pip
            --file requirements.txt
            pytest codecov pytest-cov
            --channel conda-forge

      - name: Set up conda environment
        run: |
          python -m pip install -e . --no-deps --force-reinstall

      - name: Run Tests
        run: |
          pytest -rxs --cov=./ --cov-report=xml

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
